### ISSUE TITLE
Padding on EPiServer quick navigator button

### ISSUE THREAD

**Issue by evest** [BVNetwork/CommerceStarterKit#14]
There is some strange padding or margin on the EPiServer Quick Naviagtor:
![image](https://cloud.githubusercontent.com/assets/6423464/7604384/23b2411c-f942-11e4-9da1-a19b9ca100d3.png)

This happened with the new styling.

**Comment by sveinumy** [comment]
Fixed in 462cb8b20802c8dfdf0110bbedb5268f0236e14f
