### ISSUE TITLE
Add to cart from product in content area fails

### ISSUE THREAD

**Issue by evest** [BVNetwork/CommerceStarterKit#5]
There is an animation that fails (remove it), and the cart is not updated.

See:
![image](https://cloud.githubusercontent.com/assets/6423464/7586784/bdcee9cc-f8b0-11e4-9940-3e9c8a2a358e.png)

**Comment by sveinumy** [comment]
Fixed in d92cfe9a146e29be9ad3207eee8b04047cdf3ace
