### ISSUE TITLE
Hide facets with no hits on product list page

### ISSUE THREAD

**Issue by evest** [BVNetwork/CommerceStarterKit#9]
Right now we're showing all facets in the registry. We should hide the ones that does not have any hits:
![image](https://cloud.githubusercontent.com/assets/6423464/7592474/b4a548aa-f8d3-11e4-99e2-9b43dee44674.png)

**Comment by sveinumy** [comment]
Fixed in baff9d7ee1f6edc0cc15eb7ab93e1ed510559e14
